CC = gcc

multithread:
	gcc -o multithread_practice multithread_practice.c 
	gcc -o multithread_practice_solution multithread_practice_solution.c -lpthread
	gcc -o a a.c -lpthread

clean : 
	rm multithread_practice multithread_practice_solution a